### ISSUE TITLE
Add scroll bar to the Console area

### ISSUE THREAD

**Issue by dmcassel** [paxtonhare/marklogic-debugger#15]
#### The issue

Short description of the problem:
I can paste a variable to the Console, hit enter and see the value. If I do this a few times, I can no longer see the place where I would past another value. 

What behavior are you expecting?
The cursor should always be visible, with a scrollbar so I can go back and see earlier content. 

#### Tech details

Which Operating System are you using?
Mac 10.10.5

Which version of MarkLogic are you using?
8.0-5.8

Which version of the MarkLogic Debugger are you using?
1.0.0-alpha.4

Which browser are you using?
Chrome Version 55.0.2883.95

**Comment by dmcassel** [comment]
Hitting "Clear" solves the problem, at the expense of removing previous content.

**Comment by paxtonhare** [comment]
fixed by the last commit.
